### ISSUE TITLE
进入应用后切换到我的tab栏闪退

### ISSUE THREAD

**Issue by fangxiong** [zion223/NeteaseCloudMusic-MVVM#1]
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7707)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.netease.music.domain.request.MineRequest.lambda$requestUserPlaylist$0$MineRequest(MineRequest.java:60)

**Comment by zion223** [comment]
你创建的歌单的数量是多少

**Comment by fangxiong** [comment]
> 你创建的歌单的数量是多少

首次安装进入  还没创建歌单

**Comment by fangxiong** [comment]
还发现个bug  RecommendBean的playcount需要定义为long长整型  有的歌单播放数量高json会解析错误

**Comment by zion223** [comment]
有时间改一下

**Comment by baoning2019** [comment]
D:\SourceCode\NeteaseCloudMusic-MVVM-master\app\src\main\java\com\netease\music\ui\page\cloud\CloudVillageFragment.java:11: ????: ?????????
import com.netease.music.BR;

**Comment by zion223** [comment]
> D:\SourceCode\NeteaseCloudMusic-MVVM-master\app\src\main\java\com\netease\music\ui\page\cloud\CloudVillageFragment.java:11: ????: ?????????
> import com.netease.music.BR;

你没有编译出来BR文件 ，导包的时候找不到
