### ISSUE TITLE
你好，大佬，登陆成功会后崩溃

### ISSUE THREAD

**Issue by wcglws** [zion223/NeteaseCloudMusic-MVVM#20]
第一个崩溃
 Caused by: android.view.InflateException: Binary XML file line #36 in com.netease.music:layout/activity_main: Binary XML file line #36 in com.netease.music:layout/activity_main: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #36 in com.netease.music:layout/activity_main: Error inflating class fragment
     Caused by: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:361)
        at com.netease.music.ui.page.drawer.DrawerFragment.onCreate(DrawerFragment.java:53)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)

第二个
 java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:361)
        at com.netease.music.ui.page.mine.MineFragment.onCreate(MineFragment.java:38)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)

**Comment by zion223** [comment]
手机机型和Android版本麻烦告知一下

**Comment by wcglws** [comment]
AndroidStudio模拟器   API31
![image](https://user-images.githubusercontent.com/16982083/188683275-18227291-084e-4c26-a410-8fca0ebcc2eb.png)

**Comment by SherlockGougou** [comment]
把所有 Fragment 中的onCreate换成 onViewCreated
